export const header = document.createElement('header');
export const dropDown = document.createElement('ul');
export const span = document.createElement('span');
export const nav = document.createElement('nav');
export const div = document.createElement('div');
export const navLinks = ['Women', 'Men', 'Children', 'Accesouries', 'Blog', 'Contact'];
export const ul = document.createElement('ul');
export let li = document.createElement('li');
export const languages = ['English', 'Russian'];
export const img = document.createElement('img');
export const cartPrice = ['$0.0', 'Items']
export let liForLoop = 'null';